name: Build AdminTools

on:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main


jobs:

  build:

    runs-on: ubuntu-latest


    steps:


      - name: Checkout repository
        uses: actions/checkout@v4



      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'



      - name: Make Gradle executable
        run: chmod +x gradlew



      - name: Build Mod
        run: ./gradlew build



      - name: Upload Mod Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AdminTools
          path: build/libs/*.jar
          
